src/announce/urls.py
from django.urls import path
from announce.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    delete_blog_post,
)

app_name = 'announce'

urlpatterns = [
    path('create', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
    path('delete/<slug>/', delete_blog_post, name='delete'),
]

src/blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    delete_blog_post,
)

app_name = 'blog'

urlpatterns = [
    path('create', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
    path('delete/<slug>/', delete_blog_post, name='delete'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from reservation.views import (
    begin_test_view,
    success
)

from personal.views import (
    home_screen_view,
    introduce_snt_view,
    curriculum_snt_view,
    schedule_snt_view,
    opinion_view,
    announce_view,

    # subpages
    c_lit_essay,
    c_cur_issue,
    c_debate,
    g6,
    g5,
    g4,
    g3,

)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,

)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
   
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('account/', account_view, name="account"),
    
    path('introduce/', introduce_snt_view, name="introduce"),
    
    path('announce/', announce_view, name="announce"),
    path('announce/', include('announce.urls'), name="announce"),

    path('opinion/', opinion_view, name="opinion"),
    path('opinion/', include('blog.urls'), name="blog"),


    path('curriculum/', curriculum_snt_view, name="curriculum"),
    path('curriculum/curl', c_lit_essay, name="curl"),
    path('curriculum/curc', c_cur_issue, name="curc"),
    path('curriculum/curd', c_debate, name="curd"),

    path('schedule/', schedule_snt_view, name="schedule"),
    path('schedule/g6', g6, name="g6"),
    path('schedule/g5', g5, name="g5"),
    path('schedule/g4', g4, name="g4"),
    path('schedule/g3', g3, name="g3"),

    path('leveltest/', begin_test_view, name="leveltest"),
    path('leveltest/success', success, name="success"),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),   
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/announce/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.core.validators import RegexValidator
from autoslug import AutoSlugField

slug_validator = RegexValidator(
    r'^[가-힣A-Za-z0-9_-]+$',
    'Only Korean letters, alphanumeric, hyphen, and underscore characters are allowed.'
)


def upload_location(instance, filename):
	file_path = 'announce/{author_id}/{title}-{filename}'.format(
				author_id=str(instance.author.id),title=str(instance.title), filename=filename)
	return file_path


class BlogPost(models.Model):
	class Meta:
		verbose_name = '공지사항'
		verbose_name_plural = '공지사항'
	title 					= models.CharField(verbose_name='제목', max_length=70, null=False, blank=False)
	body 					= models.TextField(verbose_name='내용', max_length=50000, null=False, blank=False)
	image		 			= models.ImageField(verbose_name='사진', upload_to=upload_location, null=True, blank=True)
	date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="업로드 일짜")
	date_updated 			= models.DateTimeField(auto_now=True, verbose_name="마지막 업데이트")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='작성자', related_name='announce_blog_posts')
	slug 					= AutoSlugField(populate_from='title', unique=True, validators=[slug_validator])

	def __str__(self):
		return self.title


@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.first_name + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

src/personal/models.py
from django.db import models

# Create your models here.

#PRIORITY = [
#	("L", "Low"),
#	("M", "Medium"),
#	("H", "High")
#]

#class Question(models.Model):
#	title 					= models.CharField(max_length=60)
#	question 				= models.TextField(max_length=400)
#	priority 				= models.CharField(max_length=1, choices=PRIORITY)

#	def __str__(self):
#		return self.title

#	class Meta:
#		verbose_name = "The Question"
#		verbose_name_plural = "Peoples Questions"

src/announce/forms.py
from django import forms
from announce.models import BlogPost

class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']
	
	

class UpdateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']

	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title = self.cleaned_data['title']
		blog_post.body = self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']

		if commit:
			blog_post.save()
		return blog_post

src/announce/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
from announce.models import BlogPost
from django.core.paginator import EmptyPage, Paginator
from announce.forms import CreateBlogPostForm, UpdateBlogPostForm
from account.models import Account

# Create your views here.

def create_blog_view(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(first_name=user.first_name).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
        return redirect('../announce')

    context['form'] = form


    return render(request, "announce/create_blog.html")

def detail_blog_view(request, slug):
    context = {}
    
    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post

    # Add pagination
    blog_posts = BlogPost.objects.all().order_by('-date_updated')
    page = request.GET.get('page', 1)
    paginator = Paginator(blog_posts, 5)  # Show 5 blog posts per page

    try:
        blog_posts = paginator.page(page)
    except EmptyPage:
        blog_posts = paginator.page(paginator.num_pages)

    context['blog_posts'] = blog_posts
    
    return render(request, 'announce/detail_blog.html', context)

	
def edit_blog_view(request, slug):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	blog_post = get_object_or_404(BlogPost, slug=slug)

	if blog_post.author != user:
		return HttpResponse('업로드인이 아닙니다.')

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "업데이트 되었습니다."
			blog_post = obj
			return redirect('../../announce')

	form = UpdateBlogPostForm(
			initial = {
					"title": blog_post.title,
					"body": blog_post.body,
					"image": blog_post.image,
			}
		)

	context['form'] = form
	return render(request, 'announce/edit_blog.html', context)


def get_blog_queryset2(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = BlogPost.objects.filter(
				Q(title__icontains=q) | 
				Q(body__icontains=q)
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))	

def delete_blog_post(request, slug):
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    blog_post = get_object_or_404(BlogPost, slug=slug)

    if blog_post.author != user:
        return HttpResponse('업로드인이 아닙니다.')

    blog_post.delete()
    return redirect('announce') 

src/personal/views.py
from account.models import Account
from django.shortcuts import render
from operator import attrgetter
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from blog.views import get_blog_queryset1
from blog.models import BlogPost
from announce.views import get_blog_queryset2
from announce.models import BlogPost

# Create your views here.
BLOG_POSTS_PER_PAGE = 10

def home_screen_view(request):
	context = {}

	accounts = Account.objects.all()
	context['accounts'] = accounts 
	return render(request, "personal/home.html", context)

def introduce_snt_view(request):
	context = {}
	accounts = Account.objects.all()
	context['accounts'] = accounts
	return render(request, "personal/introduce_snt.html", context)

# curriculums

def curriculum_snt_view(request):
	context = {}
	accounts = Account.objects.all()
	context['accounts'] = accounts
	return render(request, "personal/curriculum/curriculum_snt.html", context)


def c_lit_essay(request):
	context = {}
	accounts = Account.objects.all()
	context['accounts'] = accounts
	return render(request, "personal/curriculum/c_lit_essay.html", context)


def c_cur_issue(request):
	context = {}
	accounts = Account.objects.all()
	context['accounts'] = accounts
	return render(request, "personal/curriculum/c_cur_issue.html", context)

def c_debate(request):
	context = {}
	accounts = Account.objects.all()
	context['accounts'] = accounts
	return render(request, "personal/curriculum/c_debate.html", context)


#schedules

def schedule_snt_view(request):
	context = {}
	accounts = Account.objects.all()
	context['accounts'] = accounts
	return render(request, "personal/schedule/schedule.html", context)

def g6(request):
	context = {}
	accounts = Account.objects.all()
	context['accounts'] = accounts
	return render(request, "personal/schedule/g6.html", context)

def g5(request):
	context = {}
	accounts = Account.objects.all()
	context['accounts'] = accounts
	return render(request, "personal/schedule/g5.html", context)

def g4(request):
	context = {}
	accounts = Account.objects.all()
	context['accounts'] = accounts
	return render(request, "personal/schedule/g4.html", context)

def g3(request):
	context = {}
	accounts = Account.objects.all()
	context['accounts'] = accounts
	return render(request, "personal/schedule/g3.html", context)


def opinion_view(request):

	context = {}

	# Search
	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	blog_posts = sorted(get_blog_queryset1(query), key=attrgetter('date_updated'), reverse=True)
	
	# Pagination
	page = request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)
	try:
		blog_posts = blog_posts_paginator.page(page)
	except PageNotAnInteger:
		blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
	except EmptyPage:
		blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts'] = blog_posts

	return render(request, "personal/opinion.html", context)


def announce_view(request):

	context = {}

	# Search
	query = ""
	if request.GET:
		query = request.GET.get('q', '')
		context['query'] = str(query)

	blog_posts = sorted(get_blog_queryset2(query), key=attrgetter('date_updated'), reverse=True)
	
	# Pagination
	page = request.GET.get('page', 1)
	blog_posts_paginator = Paginator(blog_posts, BLOG_POSTS_PER_PAGE)
	try:
		blog_posts = blog_posts_paginator.page(page)
	except PageNotAnInteger:
		blog_posts = blog_posts_paginator.page(BLOG_POSTS_PER_PAGE)
	except EmptyPage:
		blog_posts = blog_posts_paginator.page(blog_posts_paginator.num_pages)

	context['blog_posts'] = blog_posts

	return render(request, "personal/announce.html", context)

src/personal/templates/personal/announce.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
	
	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}
	
	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	@media (max-width: 768px) {
    .upload-date {
        display: none;
    }
}


	.post-title {
		width: 60%;
	}
	
	.post-title a {
		color: black;
		text-decoration: none;
		
	}
	
	.post-title a:hover {
		color: darkgray;
	}
	
	
	.search-bar {
		display: flex;
		align-items: center;
		justify-content: flex-end; /* Updated this line */
	}
	
	
	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}
	
	.left-column{
		padding:0px;
	}
	
	.right-column{
		padding:0px;
	}
	
	
	.search-bar input {
		flex: 1;
		margin-right: 5px;
	}
	
	.lead{
		font-size: 17px;
	}
	
	.table-custom {
		width: 100%;
		border-collapse: collapse;
	}


	.table-custom th,
	.table-custom td {
		border: 1px solid #ddd;
		padding: 8px;
	}
	
	.table-custom th {
		text-align: center;
		background-color: #f2f2f2;
		color: black;
	}

	
</style>


<!-- main content -->
<div class="text-center">
	<h2 class="h3 mb-3 fw-normal">공지사항</h2>
	<div class="container">
		<div class="row justify-content-center">
			
			<!-- blog feed -->
			<div class="left-column col-lg-9">
				<div class="text-center">			
					<!-- end Top 'create post' bar -->
					
					<!-- Search bar -->
					<div class="search-bar mt-sm-2 mb-2">
						<form class="form-inline d-flex" method="get">
							<input class="form-control mr-sm-2" type="text" name="q" id="id_q" placeholder="검색">
							<button class="btn btn-primary" type="submit">검색</button>
						</form>
					</div>
					
					<!-- End Search bar -->
					
					<!-- Blog posts-->
					<div class="table-responsive">
						<table class="table table-custom border-top">
							<thead>
								<tr>
									<th scope="col">#</th>
									<th scope="col">제목</th>
									<th scope="col" class="upload-date">날짜</th>
									<th scope="col">작성자</th>
								</tr>
							</thead>
							<tbody>
								{% if blog_posts %}
								{% for post in blog_posts %}
								<tr>
									<td>{{ forloop.counter }}</td>
									<td class="post-title">
										{% include 'announce/snippets/blog_post_snippet.html' with blog_post=post table_view=True %}
									</td>
									<td class="upload-date">{{ post.date_updated|date:"Y년 m월 d일" }}</td>
									<td>{{ post.author.first_name }}</td>
								</tr>
								{% endfor %}							
								{% else %}
								<tr>
									<td colspan="4">포스트가 없습니다.</td>
								</tr>
								{% endif %}
							</tbody>
						</table>
					</div>
					<!-- End Blog posts-->
					{% if user.is_authenticated %}
					{% if user.is_staff or user.is_admin or user.is_superuser %}
					<div class="d-flex justify-content-end">
						<p><a class="btn btn-primary" href="{% url 'announce:create' %}">글쓰기</a></p>
					</div>
					{% endif %}
					{% endif %}
					<!-- Pagination -->
					{% include 'announce/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}
				</div>
				
			</div>
			<!-- end blog feed -->
			
		</div>
	</div>
</div>




{% endblock content %}

src/personal/templates/personal/home.html
{% extends 'base.html' %}


{% block content %}
<div class="container">
	<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
		<h4 class="display-4 fw-normal">에스엔티 제주 캠퍼스</h4>
		<p class="fs-5 text-body-secondary" style="white-space: pre-line; margin: 2rem;">SNT 제주는 제주도에 위치한 영어 토론 어학원으로, 학생들의 자신감과 능력을 향상시키는 맞춤형 교육 프로그램을 제공합니다. 
			전문적이고 경험이 풍부한 강사진과 함께 학생들은 영어를 구사하면서 논리적인 사고와 문제 해결 능력을 함양할 수 있습니다. 
			또한, 다양한 문화활동과 해외 교환 프로그램을 통해 국제적인 시각을 넓히는 기회를 제공합니다.</p>
	</div>

</div>




{% endblock content %}

src/personal/templates/personal/introduce_snt.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
	<div class="pricing-header p-3 pb-md-4 mx-auto text-center">
		<h4 class="display-4 fw-normal">에스엔티 제주 캠퍼스</h4>
		<p class="fs-5 text-body-secondary" style="white-space: pre-line; margin: 2rem;">SNT 제주는 제주도에 위치한 영어 토론 어학원으로, 학생들의 자신감과 능력을 향상시키는 맞춤형 교육 프로그램을 제공합니다. 
			전문적이고 경험이 풍부한 강사진과 함께 학생들은 영어를 구사하면서 논리적인 사고와 문제 해결 능력을 함양할 수 있습니다. 
			또한, 다양한 문화활동과 해외 교환 프로그램을 통해 국제적인 시각을 넓히는 기회를 제공합니다.</p>
	</div>

</div>

{% endblock content %}

src/personal/templates/personal/opinion.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
	
	@media (max-width: 768px) { 
		.right-column{
			margin-left: 0px;
		}
	}
	
	@media (min-width: 768px) { 
		.right-column{
			margin-left: 20px;
		}
	}

	@media (max-width: 768px) {
    .upload-date {
        display: none;
    }
}


	.post-title {
		width: 60%;
	}
	
	.post-title a {
		color: black;
		text-decoration: none;
		
	}
	
	.post-title a:hover {
		color: darkgray;
	}
	
	
	.search-bar {
		display: flex;
		align-items: center;
		justify-content: flex-end; /* Updated this line */
	}
	
	
	.blog-post-container{
		margin-bottom: 20px;
		width: 100%;
	}
	.create-post-bar{
		background-color: #fff;
		margin-bottom:20px;
	}
	
	.left-column{
		padding:0px;
	}
	
	.right-column{
		padding:0px;
	}
	
	
	.search-bar input {
		flex: 1;
		margin-right: 5px;
	}
	
	.lead{
		font-size: 17px;
	}
	
	.table-custom {
		width: 100%;
		border-collapse: collapse;
	}


	.table-custom th,
	.table-custom td {
		border: 1px solid #ddd;
		padding: 8px;
	}
	
	.table-custom th {
		text-align: center;
		background-color: #f2f2f2;
		color: black;
	}

	
</style>


<!-- main content -->
<div class="text-center">
	<h2 class="h3 mb-3 fw-normal">오피니언 게시판</h2>
	<div class="container">
		<div class="row justify-content-center">
			
			<!-- blog feed -->
			<div class="left-column col-lg-9">
				<div class="text-center">			
					<!-- end Top 'create post' bar -->
					
					<!-- Search bar -->
					<div class="search-bar mt-sm-2 mb-2">
						<form class="form-inline d-flex" method="get">
							<input class="form-control mr-sm-2" type="text" name="q" id="id_q" placeholder="검색">
							<button class="btn btn-primary" type="submit">검색</button>
						</form>
					</div>
					
					<!-- End Search bar -->
					
					<!-- Blog posts-->
					<div class="table-responsive">
						<table class="table table-custom border-top">
							<thead>
								<tr>
									<th scope="col">#</th>
									<th scope="col">제목</th>
									<th scope="col" class="upload-date">날짜</th>
									<th scope="col">작성자</th>
								</tr>
							</thead>
							<tbody>
								{% if blog_posts %}
								{% for post in blog_posts %}
								<tr>
									<td>{{ forloop.counter }}</td>
									<td class="post-title">
										{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post table_view=True %}
									</td>
									<td class="upload-date">{{ post.date_updated|date:"Y년 m월 d일" }}</td>
									<td>{{ post.author.first_name }}</td>
								</tr>
								{% endfor %}							
								{% else %}
								<tr>
									<td colspan="4">포스트가 없습니다.</td>
								</tr>
								{% endif %}
							</tbody>
						</table>
					</div>
					<!-- End Blog posts-->
					{% if user.is_authenticated %}
					{% if user.is_staff or user.is_admin or user.is_superuser %}
					<div class="d-flex justify-content-end">
						<p><a class="btn btn-primary" href="{% url 'blog:create' %}">글쓰기</a></p>
					</div>
					{% endif %}
					{% endif %}
					<!-- Pagination -->
					{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}
				</div>
				
			</div>
			<!-- end blog feed -->
			
		</div>
	</div>
</div>




{% endblock content %}