src/blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    edit_blog_view,
    delete_blog_post,
)

app_name = 'blog'

urlpatterns = [
    path('create', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),
    path('<slug>/edit', edit_blog_view, name="edit"),
    path('delete/<slug>/', delete_blog_post, name='delete'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

from reservation.views import (
    begin_test_view,
    success
)

from personal.views import (
    home_screen_view,
    introduce_snt_view,
    curriculum_snt_view,
    schedule_snt_view,
    opinion_view,
    announce_view,

    # subpages
    c_lit_essay,
    c_cur_issue,
    c_debate,
    g6,
    g5,
    g4,
    g3,

)

from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,

)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
   
    path('register/', registration_view, name="register"),
    path('logout/', logout_view, name="logout"),
    path('login/', login_view, name="login"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('account/', account_view, name="account"),
    
    path('introduce/', introduce_snt_view, name="introduce"),
    
    path('announce/', announce_view, name="announce"),
    path('announce/', include('announce.urls'), name="announce"),

    path('opinion/', opinion_view, name="opinion"),
    path('opinion/', include('blog.urls'), name="blog"),


    path('curriculum/', curriculum_snt_view, name="curriculum"),
    path('curriculum/curl', c_lit_essay, name="curl"),
    path('curriculum/curc', c_cur_issue, name="curc"),
    path('curriculum/curd', c_debate, name="curd"),

    path('schedule/', schedule_snt_view, name="schedule"),
    path('schedule/g6', g6, name="g6"),
    path('schedule/g5', g5, name="g5"),
    path('schedule/g4', g4, name="g4"),
    path('schedule/g3', g3, name="g3"),

    path('leveltest/', begin_test_view, name="leveltest"),
    path('leveltest/success', success, name="success"),


    # Password reset links (ref: https://github.com/django/django/blob/master/django/contrib/auth/views.py)
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(template_name='registration/password_change_done.html'), 
        name='password_change_done'),
    path('password_change/', auth_views.PasswordChangeView.as_view(template_name='registration/password_change.html'), 
        name='password_change'),
    path('password_reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_done.html'),
     name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='registration/password_reset_complete.html'),
     name='password_reset_complete'),   
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete
from django.dispatch import receiver
from django.core.validators import RegexValidator
from autoslug import AutoSlugField

slug_validator = RegexValidator(
    r'^[가-힣A-Za-z0-9_-]+$',
    'Only Korean letters, alphanumeric, hyphen, and underscore characters are allowed.'
)


def upload_location(instance, filename):
	file_path = 'blog/{author_id}/{title}-{filename}'.format(
				author_id=str(instance.author.id),title=str(instance.title), filename=filename)
	return file_path


class BlogPost(models.Model):
	class Meta:
		verbose_name = '오피니언'
		verbose_name_plural = '오피니언'
	title 					= models.CharField(verbose_name='제목', max_length=70, null=False, blank=False)
	body 					= models.TextField(verbose_name='내용', max_length=50000, null=False, blank=False)
	image		 			= models.ImageField(verbose_name='사진', upload_to=upload_location, null=True, blank=True)
	date_published 			= models.DateTimeField(auto_now_add=True, verbose_name="업로드 일짜")
	date_updated 			= models.DateTimeField(auto_now=True, verbose_name="마지막 업데이트")
	author 					= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, verbose_name='작성자', related_name='blog_blog_posts')
	slug 					= AutoSlugField(populate_from='title', unique=True, validators=[slug_validator])

	def __str__(self):
		return self.title


@receiver(post_delete, sender=BlogPost)
def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False) 

def pre_save_blog_post_receiver(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = slugify(instance.author.first_name + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiver, sender=BlogPost)

src/blog/forms.py
from django import forms
from blog.models import BlogPost

class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']
	
	


class UpdateBlogPostForm(forms.ModelForm):

	class Meta:
		model = BlogPost
		fields = ['title', 'body', 'image']

	def save(self, commit=True):
		blog_post = self.instance
		blog_post.title = self.cleaned_data['title']
		blog_post.body = self.cleaned_data['body']

		if self.cleaned_data['image']:
			blog_post.image = self.cleaned_data['image']

		if commit:
			blog_post.save()
		return blog_post

src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from django.http import HttpResponse
from blog.models import BlogPost
from django.core.paginator import EmptyPage, Paginator
from blog.forms import CreateBlogPostForm, UpdateBlogPostForm
from account.models import Account

# Create your views here.

def create_blog_view(request):
    context = {}
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')
    
    form = CreateBlogPostForm(request.POST or None, request.FILES or None)

    if form.is_valid():
        obj = form.save(commit=False)
        author = Account.objects.filter(first_name=user.first_name).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()
        return redirect('../opinion')

    context['form'] = form


    return render(request, "blog/create_blog.html")

def detail_blog_view(request, slug):
    context = {}
    
    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post

    # Add pagination
    blog_posts = BlogPost.objects.all().order_by('-date_updated')
    page = request.GET.get('page', 1)
    paginator = Paginator(blog_posts, 5)  # Show 5 blog posts per page

    try:
        blog_posts = paginator.page(page)
    except EmptyPage:
        blog_posts = paginator.page(paginator.num_pages)

    context['blog_posts'] = blog_posts
    
    return render(request, 'blog/detail_blog.html', context)

	
def edit_blog_view(request, slug):

	context = {}

	user = request.user
	if not user.is_authenticated:
		return redirect("must_authenticate")

	blog_post = get_object_or_404(BlogPost, slug=slug)

	if blog_post.author != user:
		return HttpResponse('업로드인이 아닙니다.')

	if request.POST:
		form = UpdateBlogPostForm(request.POST or None, request.FILES or None, instance=blog_post)
		if form.is_valid():
			obj = form.save(commit=False)
			obj.save()
			context['success_message'] = "업데이트 되었습니다."
			blog_post = obj
			return redirect('../../opinion')

	form = UpdateBlogPostForm(
			initial = {
					"title": blog_post.title,
					"body": blog_post.body,
					"image": blog_post.image,
			}
		)

	context['form'] = form
	return render(request, 'blog/edit_blog.html', context)


def get_blog_queryset1(query=None):
	queryset = []
	queries = query.split(" ") # python install 2019 = [python, install, 2019]
	for q in queries:
		posts = BlogPost.objects.filter(
				Q(title__icontains=q) | 
				Q(body__icontains=q)
			).distinct()

		for post in posts:
			queryset.append(post)

	return list(set(queryset))	

def delete_blog_post(request, slug):
    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    blog_post = get_object_or_404(BlogPost, slug=slug)

    if blog_post.author != user:
        return HttpResponse('업로드인이 아닙니다.')

    blog_post.delete()
    return redirect('opinion') 

src/blog/templates/blog/create_blog.html
{% extends 'base.html' %}


{% block content %}
<!-- include summernote css/js -->
<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<style type="text/css">
    .create-form {
        width: 100%;
        max-width: 100%;
        padding: 15px;
        margin: auto;
    }
    
    .submit-button{
        max-width: 200px;
    }
</style>
<div class="text-center">
    <h2 class="h3 mb-3 fw-normal">글쓰기</h2>
</div>
<div class="container">
    <div class="row justify-content-center">
        <div class="col-lg-9">
            <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
                
                <!-- title -->
                <div class="form-group">
                    <label for="id_title">제목</label>
                    <input class="form-control" type="text" name="title" id="id_title" placeholder="제목" required autofocus>
                </div>
                <br>
                <!-- Image -->
                <div class="form-group">
                    <label for="id_image">사진</label>
                    <input  type="file" name="image" id="id_image" accept="image/*">
                </div>
                <br>
                <!-- Body -->
                <div class="form-group">
                    <label for="id_body">내용</label>
                    <textarea class="form-control" rows="10" type="text" name="body" id="summernote" placeholder="내용" required></textarea>
                    <script>
                        $(document).ready(function() {
                            $('#summernote').summernote({
                                height: 500,                 
                                minHeight: 200,             
                                maxHeight: 1000,             
                                focus: true,
                                toolbar: [
                                ['style', ['style']],
                                ['font', ['bold', 'underline', 'clear']],
                                ['fontname', ['fontname']],
                                ['color', ['color']],
                                ['para', ['ul', 'ol', 'paragraph']],
                                ['table', ['table']],
                                ['insert', ['link', 'video']], // Remove 'picture' from this array
                                ['view', ['fullscreen', 'codeview', 'help']],
                                ],               
                            });
                        });
                    </script>
                </div>
                
                
                <!-- Submit btn -->
                <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">업로드</button>
            </form>	
        </div>
    </div>
</div>

{% endblock content %}

src/blog/templates/blog/detail_blog.html
{% extends 'base.html' %}

{% block content %}
<script>
	function confirmDelete() {
		if (confirm("정말로 이 글을 삭제하시겠습니까?")) {
			window.location.href = "{% url 'blog:delete' blog_post.slug %}";
		} else {
			return false;
		}
	}
</script>

<style type="text/css">
	.card{
		max-width: 900px;
	}
	.card-body{
		padding: 20px;
	}
	
	.post-title {
		width: 70%;
	}
	
	.post-title a {
		color: black;
		text-decoration: none;
	}
	
	.post-title a:hover {
		color: darkgray;
	}
	
	.table-custom {
		width: 100%;
		border-collapse: collapse;
	}
	
	.table-custom th,
	.table-custom td {
		border: 1px solid #ddd;
		padding: 8px;
	}
	
	.table-custom th {
		text-align: center;
		background-color: #f2f2f2;
		color: black;
	}
	
</style>

<div class="container">
	<div class="row">
		<!-- Blog Post -->
		<div class="card m-auto">
			<div class="card-body mt-2">
				<h2 class="card-title text-center">{{ blog_post.title }}</h2>
			</div>
			<div class="card-footer border-bottom text-muted d-flex justify-content-between">
				<div class="align-self-end">작성자: {{ blog_post.author.first_name }}</div>
				<div class="align-self-start">업데이트: {{ blog_post.date_updated|date:"Y년 m월 d일" }}</div>
			</div>
			{% if blog_post.image %}
			<img src="{{ blog_post.image.url }}">
			{% endif %}
			<div class="card-body mt-2 mb-2">
				<div class="d-flex flex-column">
					<p class="card-text mb-3 fs-9 text-body-secondary-dark" style="white-space: pre-line; margin: 2rem;">{{ blog_post.body|safe }}</p>
					{% if blog_post.author == request.user %}
					<div class="text-center">
						<a href="{% url 'blog:edit' blog_post.slug %}" class="btn btn-primary">글 수정</a>
						<form method="post" action="{% url 'blog:delete' blog_post.slug %}" class="d-inline">
							{% csrf_token %}
							<a href="#" class="btn btn-danger" onclick="confirmDelete()">글 삭제</a>
						</form>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
	</div>
</div>

<!-- Blog posts list -->
<div class="container mt-4">
	<div class="row justify-content-center">
		<div class="left-column col-lg-8">
			<div class="text-center">
				<br><br>
				<h5><strong>다른 글 보기</strong></h5>	
				<br>
				<div class="table-responsive">
					<table class="table table-custom">
						<thead>
							<tr>
								<th scope="col">#</th>
								<th scope="col">제목</th>
								<th scope="col">작성자</th>
							</tr>
						</thead>
						<tbody>
							{% if blog_posts %}
							{% for post in blog_posts %}
							<tr>
								<td>{{ forloop.counter }}</td>
								<td class="post-title">
									{% include 'blog/snippets/blog_post_snippet.html' with blog_post=post table_view=True %}
								</td>
								<td>{{ post.author }}</td>
							</tr>
							{% endfor %}
							{% else %}
							<tr>
								<td colspan="4">포스트가 없습니다.</td>
							</tr>
							{% endif %}
						</tbody>
					</table>
				</div>
				{% include 'blog/snippets/blog_post_pagination.html' with blog_posts=blog_posts %}
			</div>
		</div>
	</div>
</div>


{% endblock content %}

src/blog/templates/blog/edit_blog.html
{% extends 'base.html' %}


{% block content %}
<link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" rel="stylesheet">
<script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.css" rel="stylesheet">
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote.min.js"></script>
<style type="text/css">
	
	.create-form {
		width: 100%;
		max-width: 100%;
		padding: 15px;
		margin: auto;
		display: flex; /* Add this line */
		flex-direction: column; /* Add this line */
	}
	
	.submit-button {
		max-width: 200px;
		align-self: flex-end; /* Add this line */
	}
	
	.image {
		opacity: 1;
		transition: .5s ease;
		backface-visibility: hidden;
	}
	
	.middle {
		transition: .5s ease;
		opacity: 0;
		position: absolute;
		text-align: center;
		top: 50%;
		left: 50%;
		transform: translate(-50%, -50%);
		
	}
	.image-group{
		position: relative;
		text-align: center;
		cursor:pointer;
	}
	
	.image-group:hover .image {
		opacity: 0.3;
	}
	
	.image-group:hover .middle {
		opacity: 1;
	}
	
	.text {
		margin: auto;
		background-color: #4CAF50;
		color: white;
		font-size: 15px;
		padding: 15px;
	}
</style>
<div class="text-center">
	<h2 class="h3 mb-3 fw-normal">수정하기</h2>
</div>
<div class="container">
	<div class="row justify-content-center">
		<div class="col-lg-9">
			
			{% if success_message %}
			<h3 style="color:green; text-align: center;">{{success_message}}</h3>
			{% endif %}
			
			<form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}
				
				<!-- title -->
				<div class="form-group">
					<label for="id_title">제목</label>
					<input class="form-control" type="text" name="title" id="id_title" placeholder="제목" value="{{form.initial.title}}" required autofocus>
				</div>
				<!-- Image -->
				<div class="form-group image-group" id="id_image_group">
					{% if form.initial.image %}
					<img class="img-fluid image" src="{{form.initial.image.url}}" id="id_image_display">
					{% endif %}
					<div class="middle">
						<div class="text">사진 변경</div>
					</div>
				</div>
				<input type="file" name="image" id="id_image_file" accept="image/*" onchange="readURL(this)">
				<br>
				<!-- Body -->
				<div class="form-group">
					<label for="id_body">내용</label>
					<textarea class="form-control" rows="10" type="text" name="body" id="summernote" placeholder="내용" 
					required>{{form.initial.body}}</textarea>
					<script>
						$(document).ready(function() {
							$('#summernote').summernote({
								height: 500,                 
								minHeight: 200,             
								maxHeight: 1000,             
								focus: true,
								toolbar: [
                                ['style', ['style']],
                                ['font', ['bold', 'underline', 'clear']],
                                ['fontname', ['fontname']],
                                ['color', ['color']],
                                ['para', ['ul', 'ol', 'paragraph']],
                                ['table', ['table']],
                                ['insert', ['link', 'video']], // Remove 'picture' from this array
                                ['view', ['fullscreen', 'codeview', 'help']],
                                ],                   
							});
						});
					</script>
				</div>
				
				
				{% for field in form %}
				<p>
					{% for error in field.errors %}
					<p style="color: red">{{ error }}</p>
					{% endfor %}
				</p>
				{% endfor %}
				{% if form.non_field_errors %}
				<div style="color: red">
					<p>{{form.non_field_errors}}</p>
				</div>
				{% endif %}
				
				<!-- Submit btn -->
				<div class="text-center">
					<button class="submit-button btn btn-lg btn-primary btn-block" type="submit">수정하기</button>
				</div>
				
			</form>	
		</div>
	</div>
</div>

<script type="text/javascript">
	document.getElementById('id_image_group').onclick = function(event){
		document.getElementById('id_image_file').click();
	};
	
	function readURL(input){
		var reader = new FileReader();
		reader.onload = function (e) {
			$('#id_image_display')
			.attr('src', e.target.result)
		};
		reader.readAsDataURL(input.files[0]);
	}
</script>

{% endblock content %}